### ISSUE TITLE
关于play的用法

### ISSUE THREAD

**Issue by Derican** [cai-hust/manim-tutorial-CN#4]
为什么play方法仍然是一行一行执行，并非“不会阻塞而进入下一行操作”
`self.play(Write(text))`
`self.remove(text)`
仍然是显示了text的

**Comment by TonyCrane** [comment]
你是否在remove了text之后观察效果，在这之后text应该会从画面中立即消失

**Comment by Derican** [comment]
哦哦是这个意思。明白了，谢谢
